### ISSUE TITLE
Finish the path visualization

### ISSUE THREAD

**Issue by NekoSelena** [IMS-Group-7/MowerApp#11]
### Description of the task
On the main screen, the user will be able to see the path of the robot ( [#7](https://github.com/IMS-Group-7/MowerApp/issues/7) ). To do after all the missing screens are integrated and the app complete

---

### User story
As a user, I want to visualize my robot's path to see what it is doing when I am piloting it

---

### Definitions of Done
- [x] The path visualization is intergrated to the finished app

**Comment by baan20ty** [comment]
Path is implemented. @TypoTami
