### ISSUE TITLE
Connect the robot and the app

### ISSUE THREAD

**Issue by NekoSelena** [IMS-Group-7/MowerApp#4]
### Description of the task
The app must be connected to the robot for the user to use it

---

### User story
As a user, I want to connect the app with the robot to drive it via the app

---

### Definitions of Done
- [x] After validation of the research, the chosen connection is integrated to the app
  - [x] Web sockets are used to connect them
  - [x] The app is a client of the backend

**Comment by baan20ty** [comment]
App is connected to websocket now, but will be changed to socket.io to fit the backend. @aljonasamuelsson @MerlinJallu
