### ISSUE TITLE
Sending driving commands

### ISSUE THREAD

**Issue by NekoSelena** [IMS-Group-7/MowerApp#5]
### Description of the task
Once the app is connected to the robot, the user can use it to drive the robot

---

### User story
As a user, I want to drive the robot with the app

---

### Definitions of Done
- [x] Clicking on the directionnal arrows sends the corresponding driving command to the RaspberryPi

**Comment by baan20ty** [comment]
App is able to request commands to the backend which then sends the commands to the Raspberr Pi
